apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-storage
  labels:
    type: local
spec:
  accessModes: 
    - ReadWriteOnce
  capacity: 
    storage: 5Gi
  hostPath: 
    path: /mnt/data
  storageClassName: manual
  